name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: 'latest'

jobs:
  artifact_webview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install Webview
        run: |
          git clone https://github.com/webview/webview.git
          rm -rf webview/.git

      - uses: actions/upload-artifact@v2
        with:
          name: webview
          path: webview

  release:
    runs-on: ubuntu-latest
    needs: [artifact_webview]
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: ./dist
        
      - name: Build zip
        run: |
          cp meson.build dist/meson.build
          cd dist
          zip -r webview.zip webview/*
          zip -r meson.zip meson.build

      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: ${{ github.event.inputs.tag }}
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./dist/*.zip