name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: 'latest'

jobs:
  artifact_webview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install Webview
        run: |
          git clone https://github.com/webview/webview.git
          rm -rf webview/.git

      - uses: actions/upload-artifact@v2
        with:
          name: webview
          path: webview

  release:
    runs-on: ubuntu-latest
    needs: [artifact_webview]
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: ./dist
        
      - name: Build zip
        run: |
          cd dist/webview
          zip -r webview.zip .
          cd ..
          cp webview/webview.zip .
          mkdir webview_webview-${{ github.event.inputs.tag }}
          cp ./../meson.build webview_webview-${{ github.event.inputs.tag }}
          zip -r meson.zip webview_webview-${{ github.event.inputs.tag }}
          cd ..
      
      - name: wrap meson
        run: |
          sed -i "s/_VERSION_/${{ github.event.inputs.tag }}/g" webview-meson.wrap
          MESON_HASH=$(sha256sum dist/meson.zip | cut -d ' ' -f 1)
          sed -i "s/_MESON_HASH_/$MESON_HASH/g" webview-meson.wrap
          WEBVIEW_HASH=$(sha256sum dist/webview.zip | cut -d ' ' -f 1)
          sed -i "s/_WEBVIEW_HASH_/$WEBVIEW_HASH/g" webview-meson.wrap

      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: ${{ github.event.inputs.tag }}
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./dist/*.zip
            webview-meson.wrap