name: Make release tag

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Delete tag and release
        uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: latest

      - name: New tag & launch release process
        run: |
          echo "Tagging latest"
          git tag latest
          git push --tags
          # Explicitly run our release workflow for this new tag
          gh workflow run release.yml --ref latest